name: Notify Zendesk Guide Update to Slack

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour

jobs:
  zendesk_guide_slack_job:
    runs-on: ubuntu-22.04
    name: Zendesk Guide to Slack
    steps:
      - id: last-execution
          name: Get the last execution time
          run: |
            LAST_RUN=$(curl -fsSL "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/runs" | jq -r '.workflow_runs | map(select(.status == "completed"))[0].created_at')
            if [ -z "$LAST_RUN" ]; then
              echo "No previous runs found. Defaulting to 1 hour ago."
              LAST_RUN=$(date -d "1 hour ago" +%s)
            else
              LAST_RUN=$(date -d "$LAST_RUN" +%s)
            fi
            echo "last_run_time=$LAST_RUN" >> $GITHUB_OUTPUT

      - name: Debug Repository and Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow File: main.yml"
          echo "Current Actor: ${{ github.actor }}"
          echo "Repository Owner: ${{ github.repository_owner }}"


          
      - id: guide
        name: Pull Guide update
        run: |
          ARTICLES=$(curl -fsSL -X GET -H 'Content-type: application/json; charset=utf-8' \
          -u ${{ secrets.ZENDESK_EMAIL }}/token:${{ secrets.ZENDESK_TOKEN }} \
          "https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/api/v2/help_center/incremental/articles?start_time=${{ steps.last-execution.outputs.last_run_time }}" | jq -r '.articles[] | [.title, .updated_at, .html_url] | @json')
          if [ -z "$ARTICLES" ]; then
            echo "No articles found."
            ARTICLES="No updates found since last run."
          fi
          echo "articles=$ARTICLES" >> $GITHUB_OUTPUT

      - id: slack
        name: Notify Slack
        run: |
          if [ "${{ steps.guide.outputs.articles }}" == "No updates found since last run." ]; then
            echo "No updates to send to Slack."
            exit 0
          fi
          curl -X POST -H "Content-type: application/json; charset=utf-8" \
          -d "{\"text\": \"Recent Article Updates:\n${{ steps.guide.outputs.articles }}\"}" \
          ${{ secrets.SLACK_WEBHOOK }}
